version: "3.9"
   
services:
  db:
    image: postgres
    container_name: database
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: ./django_image
    container_name: django-daphne #specify the container name to align with install_spa_to_server.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mai_shogi_project
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - db

  nginx:
    container_name: nginx-server
    build: ./nginx_image
    volumes: ./nginx_image/nginx
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      - DAPHNE_PORT=8000
      - DAPHNE_HOST=django-daphne

  redis_cache:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
