version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./server_image
    container_name: server-web-1 #specify the container name to align with install_spa_to_server.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mai_shogi_project
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis-cache
    depends_on:
      - db
  redis_cache:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
